name: Publish config_test_rp2040_general

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/config_test_rp2040_general.yaml"
      - "config_test_rp2040_general/**"

defaults:
  run:
    working-directory: config_test_rp2040_general

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload to Firmix
        run: |
          curl --fail-with-body -X POST -H "Authorization: token ${{secrets.FIRMIX_TOKEN}}" \
            -F readme=@./readme.md -F thumbnail=@./thumbnail.jpg \
            -F project=@./firmix.project.json -F board=@./firmix.board.json \
            -F firmware=@./.pio/build/generic/firmware.uf2 \
            https://firmix.deno.dev/api/project/upload
