name: Publish example_pipi_gherkin

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/example_pipi_gherkin.yaml"
      - "firmix-kfx/example_pipi_gherkin/**"

defaults:
  run:
    working-directory: firmix-kfx/example_pipi_gherkin

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload to Firmix
        run: |
          curl --fail-with-body -X POST -H "Authorization: token ${{secrets.FIRMIX_TOKEN}}" \
            -F readme=@./readme.md -F project=@./firmix.project.json -F thumbnail=@./thumbnail.jpg \
            -F firmware=@./.pio/build/generic/firmware.uf2 \
            https://firmix-kfx.nector.me/api/project/upload
